name:                splendour
version:             0.1.0.0
github:              "Sventimir/splendour"
license:             BSD3
author:              "Sventimir & Agentka 00111"
maintainer:          "svantimir@gmail.com"
copyright:           "2021 Sventimit & Agentka 00111"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/splendour#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  splendour-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - splendour

tests:
  splendour-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - splendour
